# Generated by Django 2.1.4 on 2018-12-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
