# Generated by Django 2.1.4 on 2018-12-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
