# Generated by Django 2.1.4 on 2019-01-02 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181231_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='publish_data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
