# Generated by Django 2.1.4 on 2019-01-02 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190101_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='New Title', max_length=250, unique=True, verbose_name='Post Title'),
        ),
    ]
